{"uuid": "da473ef3-d45a-4e82-ad7f-94ad3559e2e3", "befores": [{"name": "auth_token", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 200\n +  where 401 = <Response [401 Unauthorized]>.status_code\n", "trace": "  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pytest_asyncio\\plugin.py\", line 681, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\User\\secure-auth-api\\tests\\conftest.py\", line 91, in auth_token\n    assert response.status_code == 200\n"}, "start": 1754499083530, "stop": 1754499083539}], "start": 1754499083530, "stop": 1754499083613}